### ISSUE TITLE
UTF8 configuration files are not supported

### ISSUE THREAD

**Issue by israelvaldez** [microsoft/windows-container-tools#32] opened 2020-11-10 23:46 UTC
When creating a configuration file with the following code you get the following error when running the LogMonitor.exe program.

Error:
`
[2020-11-10T23:42:02.000Z][LOGMONITOR] ERROR: Failed to read json configuration file. JsonFileParser: Error reading a valid value.
[2020-11-10T23:42:02.000Z][LOGMONITOR] ERROR: Invalid configuration file.
`

Powershell repro:
`
$var  = @"
{
  "LogConfig": {
    "sources": [
      {
        "type": "EventLog",
        "startAtOldestRecord": true,
        "eventFormatMultiLine": false,
        "channels": [
          {
            "name": "system",
            "level": "Error"
          }
        ]
      }
    ]
  }
}
"@

$var | Out-File -FilePath "C:\LogMonitor\LogMonitorConfig.json" `
  -Encoding utf8
`

Only when you use -Encoding ascii is when you're able to get LogMonitor.exe to read the file

**Comment by davidharcourt** [comment] 2021-02-12 15:10
I've just hit the same issue but it's not UTF8 encoding per se (at least, in my case), but the Byte Order Mark that was causing the problem. Re-saved the config file without it and it worked perfectly

**Comment by profnandaa** [comment] 2022-06-13 09:01
Duplicate of #38, PR raised.

**Closed** 2022-08-08 12:06 UTC
Labels: bug
