### ISSUE TITLE
[BUG] ][LOGMONITOR] ERROR: Failed to query next event. Error: 21.

### ISSUE THREAD

**Issue by israelvaldez** [microsoft/windows-container-tools#163] opened 2023-11-01 17:23 UTC
**Describe the bug**
Suddenly some of my containers present the following error, which leaves them hanging on forever in kubernetes.

**To Reproduce**
1. Run a container with the following configuration of entrypoint:
```
SHELL ["cmd", "/S", "/C"]
ENTRYPOINT ["cmd", "/S", "/C", "powershell","-command", "./Scripts/Run.ps1", "&&", "C:/LogMonitor/LogMonitor.exe", "ServiceMonitor.exe", "w3svc"]
```
3. With a configuration for logmonitor.exe being the following:
```JSON
{
    "LogConfig": {
        "sources": [{
                "eventFormatMultiLine": false,
                "channels": [{
                        "level": "error",
                        "name": "system"
                    }, {
                        "level": "Error",
                        "name": "application"
                    }
                ],
                "type": "EventLog",
                "startAtOldestRecord": true
            }, {
                "filter": "*.log",
                "includeFileNames": true,
                "directory": "c:\\inetpub\\logs",
                "includeSubdirectories": true,
                "type": "File"
            }, {
                "filter": "*.txt",
                "includeFileNames": true,
                "directory": "C:\\epi\\logs",
                "includeSubdirectories": true,
                "type": "File"
            }
        ]
    }
}

```
5. Suddenly at some point the pod stops running with the following errors
```
2023-10-31T01:10:57.842902400Z [2023-10-31T01:10:57.000Z][LOGMONITOR] ERROR: Failed to query next event. Error: 21.
2023-10-31T01:10:57.842902400Z [2023-10-31T01:10:57.000Z][LOGMONITOR] ERROR: Failed to start event log monitor. Error: 21
2023-11-01T12:29:07.102387200Z [2023-11-01T12:29:07.000Z][LOGMONITOR] ERROR: Error monitoring log directory. Invalid directory change notification data.
2023-11-01T12:29:07.102467400Z [2023-11-01T12:29:07.000Z][LOGMONITOR] ERROR: Error monitoring log directory. Invalid directory change notification data.
```

**Expected behavior**
Logmonitor.exe should exit with code 1 if there's a catastrophic error or it should report something that we can act on to correct the issue.

**Configuration**
Specified in steps to reproduce

**Additional context**
I collected memory dumps of the process as it was hanging, if you need me to send them I can send it to you independently via email.

**Comment by iankingori** [comment] 2023-11-01 20:26
Hey @israelvaldez, which version of Log Monitor are you running?

**Comment by israelvaldez** [comment] 2023-11-01 20:36
According to the .exe file version it is 2.0.0
![image](https://github.com/microsoft/windows-container-tools/assets/38796159/00f50d01-3a17-48ca-93aa-7360980c82c6)

**Comment by iankingori** [comment] 2023-11-01 20:56
Thanks, and which base image are you using?

**Comment by israelvaldez** [comment] 2023-11-01 21:02
mcr.microsoft.com/dotnet/framework/wcf:4.8-windowsservercore-ltsc2019

**Comment by iankingori** [comment] 2023-11-01 21:13
We'll try to repro this, we had a similar issue on the 2019 dotnet images: https://github.com/microsoft/windows-container-tools/issues/150. It was fixed in [version 2.0.2](https://github.com/microsoft/windows-container-tools/releases/tag/v2.0.2). This seems to be impacting file monitor as well which is strange.

**Comment by bobsira** [comment] 2023-11-05 23:30
Hiya @israelvaldez can you confirm if these errors appear on the latest version of Log Monitor that Ian pointed out. v2.0.2.

I tried repro it on my end and I did not see any regression.

===these are the logs I could observe 

```
[2023-11-05T23:17:13.000Z][LOGMONITOR] INFO: Log directory \\?\C:\epi\logs does not exist. LogMonitor will wait for 300 seconds for the directory to be created.
[2023-11-05T23:17:13.000Z][LOGMONITOR] INFO: Waiting for system event channel to be enabled
[2023-11-05T23:17:28.000Z][LOGMONITOR] INFO: Enabled system event channel after 0 seconds.
{"Source": "EventLog","LogEntry": {"Time": "2023-10-10T19:35:59.000Z","Channel": "System","Level": "Error","EventId": 7023,"Message": "The Server service terminated with the following error: \r\nThe system cannot find the file specified."}}
{"Source": "EventLog","LogEntry": {"Time": "2023-10-10T19:35:59.000Z","Channel": "System","Level": "Error","EventId": 701,"Message": "Task Scheduler service failed to start Task Compatibility module. Tasks may not be able to register on previous Window versions. Additional Data: Error Value: 2147942450."}}
{"Source": "EventLog","LogEntry": {"Time": "2023-10-10T19:35:59.000Z","Channel": "System","Level": "Error","EventId": 701,"Message": "Task Scheduler service failed to start Task Compatibility module. Tasks may not be able to register on previous Window versions. Additional Data: Error Value: 2147942450."}}
{"Source": "EventLog","LogEntry": {"Time": "2023-10-10T19:53:34.000Z","Channel": "System","Level": "Error","EventId": 701,"Message": "Task Scheduler service failed to start Task Compatibility module. Tasks may not be able to register on previous Window versions. Additional Data: Error Value: 2147942450."}}
{"Source": "EventLog","LogEntry": {"Time": "2023-10-10T19:53:34.000Z","Channel": "System","Level": "Error","EventId": 701,"Message": "Task Scheduler service failed to start Task Compatibility module. Tasks may not be able to register on previous Window versions. Additional Data: Error Value: 2147942450."}}
{"Source": "EventLog","LogEntry": {"Time": "2023-10-10T19:53:34.000Z","Channel": "System","Level": "Error","EventId": 7023,"Message": "The Server service terminated with the following error: \r\nThe system cannot find the file specified."}}
{"Source": "EventLog","LogEntry": {"Time": "2023-10-10T19:55:53.000Z","Channel": "System","Level": "Error","EventId": 701,"Message": "Task Scheduler service failed to start Task Compatibility module. Tasks may not be able to register on previous Window versions. Additional Data: Error Value: 2147942450."}}
{"Source": "EventLog","LogEntry": {"Time": "2023-10-10T19:55:53.000Z","Channel": "System","Level": "Error","EventId": 701,"Message": "Task Scheduler service failed to start Task Compatibility module. Tasks may not be able to register on previous Window versions. Additional Data: Error Value: 2147942450."}}
{"Source": "EventLog","LogEntry": {"Time": "2023-10-10T19:55:53.000Z","Channel": "System","Level": "Error","EventId": 7023,"Message": "The LanmanServer service terminated with the following error: \r\nThe system cannot find the file specified."}}
{"Source": "EventLog","LogEntry": {"Time": "2023-10-10T19:56:28.000Z","Channel": "System","Level": "Error","EventId": 701,"Message": "Task Scheduler service failed to start Task Compatibility module. Tasks may not be able to register on previous Window versions. Additional Data: Error Value: 2147942450."}}
{"Source": "EventLog","LogEntry": {"Time": "2023-10-10T19:56:28.000Z","Channel": "System","Level": "Error","EventId": 701,"Message": "Task Scheduler service failed to start Task Compatibility module. Tasks may not be able to register on previous Window versions. Additional Data: Error Value: 2147942450."}}
{"Source": "EventLog","LogEntry": {"Time": "2023-10-10T19:56:28.000Z","Channel": "System","Level": "Error","EventId": 7023,"Message": "The LanmanServer service terminated with the following error: \r\nThe system cannot find the file specified."}}
```

**Comment by lucillex** [comment] 2023-11-07 23:23
Hi @israelvaldez, would you be able to send the memory dumps collected to WindowsContainerGitHubIssues@service.microsoft.com?

**Comment by israelvaldez** [comment] 2023-11-08 12:28
Sent.

**Comment by israelvaldez** [comment] 2023-11-08 12:39
Seems WindowsContainerGitHubIssues@service.microsoft.com is not setup correctly as I recieved a message from postmaster@microsoft.com saying that address isn't setup to recieve messages from my email address.


```
Your message to the Microsoft 365 group WindowsContainerGitHubIssues@service.microsoft.com couldn't be delivered.

The group WindowsContainerGitHubIssues isn't set up to receive messages from .


Office 365 	WindowsContainerGitH. . . 
Sender 		Action Required 
 	 	 	 	 

		Sender not allowed 
```

**Comment by lucillex** [comment] 2023-11-08 18:22
Would you be able to try again? There was a policy preventing external emails but that's fixed now.

**Comment by bobsira** [comment] 2023-11-21 13:45
Hello @israelvaldez, we are working on how to handle catastrophic failures in Log Monitor. We've not been able to repro the issue on our end. Could you please share your Docker file? Thanks!

**Comment by lucillex** [comment] 2023-12-08 19:38
@israelvaldez please send the files to WindowsContainerGitHubIssues@service.microsoft.com

**Closed** 2024-01-16 12:56 UTC
Labels: bug
